### ISSUE TITLE
type object 'Settings' has no attribute 'all'

### ISSUE THREAD

**Issue by daicoolb** [django-wiki/django-wiki#686] opened 2017-09-06 09:31 UTC
Request Method: | GET
-- | --
http://10.239.82.109:8000/_settings/
1.11.4
AttributeError
type object 'Settings' has no attribute 'all'
/home/liujie/.local/lib/python2.7/site-packages/django/forms/models.py in __deepcopy__, line 1186
/usr/bin/python
2.7.12
['/home/liujie/django-wiki/testproject',  '/home/liujie/caffe/python',  '/home/liujie/django-wiki/testproject',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/home/liujie/.local/lib/python2.7/site-packages',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages/PILcompat',  '/usr/lib/python2.7/dist-packages/gtk-2.0',  '/home/liujie/django-wiki/testproject/testproject',  '/home/liujie/django-wiki/testproject',  '/usr/local/lib/python2.7/dist-packages/IPython/extensions']
Wed, 6 Sep 2017 11:30:25 +0200

**Comment by benjaoming** [comment] 2017-09-06 10:46
@daicoolb - would you mind posting the traceback??

**Comment by benjaoming** [comment] 2017-09-06 10:48
This is a duplicate of #676

**Closed by benjaoming** 2017-09-06 10:48 UTC
