### ISSUE TITLE
Image tags are replaced inside <code>

### ISSUE THREAD

**Issue by citxx** [django-wiki/django-wiki#899] opened 2018-08-02 13:43 UTC
If you put an image tag inside backticks it gets replaced with an image, but probably shouldn't. Example: `` `[image:47 size:large]` ``

**Comment by benjaoming** [comment] 2018-08-02 14:20
I think this might be fixed by #896 - if you have time, you could give input to @Mortal about the PR? It's just a few days old.

**Comment by Mortal** [comment] 2018-08-02 14:55
Agreed - I'm working on a fix for this. The issue is that parsing of [image...] happens in preprocessing, before backticks are parsed. However, if I recall correctly, the image tag allows adding a caption afterwards, which is a bit tricky to refactor into a so-called inline processor.

**Comment by Mortal** [comment] 2018-08-03 10:47
This issue is now fixed by #896.

**Closed** 2020-01-07 00:52 UTC
