### ISSUE TITLE
Slug validation error.

### ISSUE THREAD

**Issue by mrmikee** [django-wiki/django-wiki#407] opened 2015-04-07 11:33 UTC
Slug validation error when '-' is part of slug.   Our needed slug names contain this allowed character, per your field hint pop up, yet form validation fails on the slug field for example "xxx-yyyy-atl" will fail, but should not.

**Comment by benjaoming** [comment] 2015-04-07 11:48
Duplicate of #391

**Closed by benjaoming** 2015-04-07 11:48 UTC
