### ISSUE TITLE
Macros broken: Markdown from pip install (v2.6.2) is not compatible with wiki 0.0.24

### ISSUE THREAD

**Issue by ethoms** [django-wiki/django-wiki#425] opened 2015-05-07 21:51 UTC
The version of Markdown that is installed by default when installing wiki from pip is v2.6.2. The macros does not work with this version of Markdown.

Workaround: uninstall Markdown and install version 2.3.1 (pip install Markdown==2.3.1).

Suggestion: the pypi dependency should be set for a working version of Markdown.

I'm using Python version 3.4 and Django version 1.6.11.

**Comment by benjaoming** [comment] 2015-05-07 21:55
This is fixed in current master branch. See:

https://github.com/django-wiki/django-wiki/blob/master/setup.py

and

https://github.com/django-wiki/django-wiki/commit/d3b0417acf8599625e7a196d1e65b62c42436015

I would think it's a duplicate of #406

**Closed by benjaoming** 2015-05-07 21:55 UTC
