### ISSUE TITLE
syntax error in notifications plugin

### ISSUE THREAD

**Issue by georgekpg** [django-wiki/django-wiki#1047] opened 2020-04-14 15:47 UTC
Hi, all

wiki/plugins/notifications/views.py in get_context_data on line 47-48

def get_context_data(self, **kwargs):
    context = super().get_context_data(self, **kwargs)

Obviously, should be 

    context = super().get_context_data(**kwargs)     

Django 2.2.12  wiki 0.5 (cannot use 0.6 because of django-mptt requirement is too high)

**Comment by benjaoming** [comment] 2020-04-14 16:22
Hi @georgekpg 

We're working on 0.6 now, but I've added a branch for patch releases, `releases/0.5.x`, you're welcome to fix it there.

The issue is already fixed in `master` and 0.6 (beta) https://github.com/django-wiki/django-wiki/blob/master/src/wiki/plugins/notifications/views.py#L53

**Comment by oscarmcm** [comment] 2022-12-20 19:58
Closing this as this was already solved in 0.6

**Closed by oscarmcm** 2022-12-20 19:58 UTC
Labels: bug
