### ISSUE TITLE
syncdb - No module named plugins

### ISSUE THREAD

**Issue by murtaghj** [django-wiki/django-wiki#638] opened 2017-05-08 13:45 UTC
Hi Guys, 

This looks like a very good project basically exactly what I need but im having issues getting it to work. When trying to do a syncdb I get the following error message;

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/wiki/Env/wikisite/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/wiki/Env/wikisite/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/wiki/Env/wikisite/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/wiki/Env/wikisite/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/wiki/Env/wikisite/lib/python2.7/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named plugins

my installed apps are shown below;

bleach (1.5.0)
Django (1.10.7)
django-classy-tags (0.8.0)
django-mptt (0.8.7)
django-nyt (1.0b2)
django-sekizai (0.10.0)
gunicorn (19.7.1)
html5lib (0.9999999)
Markdown (2.6.8)
MySQL-python (1.2.5)
olefile (0.44)
Pillow (4.1.1)
pip (9.0.1)
pytz (2017.2)
setuptools (28.8.0)
six (1.10.0)
sorl-thumbnail (12.3)
uWSGI (2.0.15)
wheel (0.29.0)
wiki (0.2.4)
yolk (0.4.3)

my installed apps are shown below;

INSTALLED_APPS = [
    'django.contrib.humanize',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admin',
    'django.contrib.admindocs',
    'sekizai',
    'sorl.thumbnail',
    'django_nyt',
    'wiki',
    'wiki.plugins.macros',
    'wiki.plugins.help',
    'wiki.plugins.links',
    'wiki.plugins.images',
    'wiki.plugins.attachments',
    'wiki.plugins.notifications',
    'wiki.plugins.globalhistory',
    'mptt',
]

Has anybody got any idea why this wont work?

**Comment by benjaoming** [comment] 2017-05-08 20:06
Dupe of #594

**Comment by benjaoming** [comment] 2017-05-08 20:06
Why open up a new issue after I responded to your comment on the already existing issue?

**Closed by benjaoming** 2017-05-08 20:06 UTC
