### ISSUE TITLE
Track paragraph changes and inject unique IDs in <p> elements

### ISSUE THREAD

**Issue by pknowles** [django-wiki/django-wiki#296] opened 2014-08-21 06:01 UTC
I'm not sure if this can already be implemented or if it's not worth the effort. I came across [this post](http://stackoverflow.com/questions/1049272/unable-to-find-build-a-commenting-system-similar-as-at-djangobook) on SO. I quite like the idea of inline commenting, especially for collaborative writing, and was wondering how easy it would be to implement with django-wiki. Of course the commenting system should be separate, I'm just interested in tracking and exposing changes to the wiki content.

**Comment by benjaoming** [comment] 2015-12-27 00:20
Closing as a duplicate of #180

**Closed** 2020-01-07 02:02 UTC
